#
# MIT License
#
# (C) Copyright 2025 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# tasks file for ct_test
- name: prereqs
  block:
    - name: fail if missing extra vars
      fail:
        msg: "{{ item }} is not set or empty"
      when: item is not defined or item == ""
      loop:
        - "{{ api_results_file }}"
        - "{{ goss_file }}"
        - "{{ goss_output_file }}"
        - "{{ dst_formatted_output_file }}"
        - "{{ package_manager }}"

    - name: get csm versions
      command: kubectl -n services get cm cray-product-catalog -o jsonpath='{.data.csm}'
      register: csm_versions
      failed_when: csm_versions.rc != 0

    # loop through the csm versions and set the csm_version variable to the last
    - name: set csm version needed for api results
      set_fact:
        csm_version: "{{ csm_versions.stdout | from_yaml | list | last }}"

# this role runs the goss tests and formats the results to be compatible with DST
# it is assumed that the environment is already set up for the test being called
# for example, to test if multi-tenancy works, a tenant should already be created
# this will vary for each test, but this role simply runs the goss tests and formats the results
- name: run goss tests from a given goss_file
  command: "goss -g {{ goss_file }} --package {{ package_manager }} validate --format json"
  register: goss_result
  # fails if
  #   - the return code is non‑zero 
  #   - the stdout is not valid (or empty) JSON
  # if a test fails, the return code is zero, but it we still want to get all out valid json
  failed_when: >
    (goss_result.rc != 0)
    and
    ((goss_result.stdout | default("{}") | from_json | length) == 0)
  changed_when: >
    (goss_result.stdout | from_json | length) > 0

- name: write raw goss results to file for debug
  copy:
    content: "{{ goss_result.stdout | to_nice_json }}"
    dest: "{{ goss_output_file }}"
    mode: '0644'
  when: goss_result is defined and goss_result.stdout is defined

- name: initialize dst_results
  set_fact:
    dst_formatted_results:
      run_id: ""
      tests: []
      triage: {}
  when: goss_result is defined and goss_result.stdout is defined

# goss output is not directly compatible with dst, so we need to transform it
# this is the same as what the pipeline shell script does
- name: transform goss results to dst format
  set_fact:
    dst_formatted_results: "{{ dst_formatted_results | combine({
        'tests': dst_formatted_results.tests + [
          {
            'product_name': 'CSM',
            'product_version': csm_version | default(''),
            'release_name': '',
            'release_version': '',
            'output': item.successful | ternary('omitted', (item.stderr | default(''))),
            'status': item.successful | ternary('pass', 'fail'),
            'label': item['resource-type'] | default(''),
            'test_name': item.title | default(''),
            'id': item['resource-id'] | default(''),
            'test_artifacts': item
          }
        ]
      }, recursive=True) }}"
  loop: "{{ (goss_result.stdout | from_json).results }}"
  loop_control:
    label: "{{ item['summary-line'] | default('No summary line') }}"
  when: goss_result is defined and goss_result.stdout is defined

- name: write dst-formatted results to file for debug
  copy:
    content: "{{ dst_formatted_results | to_nice_json }}"
    dest: "{{ dst_formatted_output_file }}"
    mode: '0644'
  when: goss_result is defined and goss_result.stdout is defined and dst_formatted_results is defined

- name: merge all dst_formatted_results .tests with existing results file
  block:
    - name: read formatted goss results file
      slurp:
        src: "{{ dst_formatted_output_file }}"
      register: formatted_file_content
    
    - name: check if api-results file exists
      stat:
        path: "{{ api_results_file }}"
      register: api_results_file_stat

    - name: create an empty api-results file if it does not exist
      copy:
        content: '{"run_id": "", "tests": [], "triage": {}}'
        dest: "{{ api_results_file }}"
        mode: '0644'
      when: not api_results_file_stat.stat.exists

    - name: read existing api results file
      slurp:
        src: "{{ api_results_file }}"
      register: api_results_pre_file_content
    
    - name: parse json content
      set_fact:
        formatted_goss: "{{ formatted_file_content['content'] | b64decode | from_json }}"
        api_results_pre: "{{ api_results_pre_file_content['content'] | b64decode | from_json }}"
    
    - name: create merged result
      set_fact:
        merged_result:
          run_id: "{{ formatted_goss.run_id | default('') }}"
          tests: "{{ (formatted_goss.tests | default([])) + (api_results_pre.tests | default([])) }}"
          triage: "{{ formatted_goss.triage | default({}) | combine(api_results_pre.triage | default({})) }}"
    
    - name: write merged result to file
      copy:
        content: "{{ merged_result | to_nice_json }}"
        dest: "{{ api_results_file }}"
        mode: '0644'

    - name: read existing api results file
      slurp:
        src: "{{ api_results_file }}"
      register: api_results_post_file_content
    
    - name: parse json content
      set_fact:
        api_results_post: "{{ api_results_post_file_content['content'] | b64decode | from_json }}"

    - name: Show summary
      debug:
        msg: 
          - "Merged goss results into {{ api_results_file }}"
          - "Tests from {{ goss_file | basename }}: {{ dst_formatted_results.tests | length }}"
          - "Total tests in {{ api_results_file | basename }} before this run: {{ api_results_pre.tests | length }}"
          - "Total tests in {{ api_results_file | basename }} after merge: {{ api_results_post.tests | length }}"
