#!/usr/bin/env bash
#
# MIT License
#
# (C) Copyright 2021-2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

# GOSS_BASE should already be set on the PIT node, but just in case we
# will set it here
export GOSS_BASE=${GOSS_BASE-"/opt/cray/tests/install/livecd"}

source "${GOSS_BASE}/automated/run-ncn-tests.sh"

export GOSS_FILE="${GOSS_BASE}/suites/livecd-provisioning-tests.yaml"

# The create_tmpvars_file function is defined in run-ncn-tests.sh
# It creates the temporary variables file and saves the path to it in the ${tmpvars} variable
create_tmpvars_file || exit 1

echo $'\e[1;33m'Running LiveCD provisioning checks \(may take a few minutes to complete\)...$'\e[0m'

# Run the LiveCD provisioning Goss test suite
export GOSS_VARS=${tmpvars}

/usr/bin/goss validate -f json | "${GOSS_BASE}/automated/print_goss_json_results" --input - ||
	err_exit $'\e[1;31m'"There were test errors"$'\e[0m'

echo "All tests passed!"
exit 0
