#!/usr/bin/env bash
#
# (C) Copyright 2021 Hewlett Packard Enterprise Development LP.
# Author: Forrest Jadick
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

# GOSS_BASE isn't set by default on the NCNs, just on LiveCD
[[ -z $GOSS_BASE ]] && export GOSS_BASE="/opt/cray/tests/install/ncn"

source $GOSS_BASE/automated/run-ncn-tests.sh

echo $'\e[1;33m'Spire Health Checks$'\e[0m'
echo $'\e[1;33m'-------------------$'\e[0m'

# find the ncn node names and query the server endpoint
if [ -f "/etc/dnsmasq.d/statics.conf" ]; then
  cat /etc/dnsmasq.d/statics.conf | grep -ohE "ncn-[m,w]([0-9]{3})" | grep -v ncn-m001 | awk '!a[$0]++' | \
    while read node ; do run_ncn_tests "$node" "9003" "ncn-spire-healthchecks" ; done
else
  cat /etc/hosts | grep -ohE "ncn-[m,w]([0-9]{3})" | awk '!a[$0]++' | while read node ; do run_ncn_tests "$node" "9003" \
    "ncn-spire-healthchecks" ; done
fi

# Specify the spire postgres clusters and call the postgres tests.
# This only needs to be done once on the NCN that this script is
# executing on as the postgres tests include all of the members of
# the cluster.

export CLUSTER_NAME=spire-postgres
export CLUSTER_NS=spire

echo $'\n\e[1;33m'---------------$'\e[0m'
echo $'\e[1;33m'NCN Spire Postgres Pods Running$'\e[0m'
echo "Test Name: goss-k8s-postgres-pods-running"
echo "Description: Validate that spire postgres pods are running."
goss -g  /opt/cray/tests/install/ncn/tests/goss-k8s-postgres-pods-running.yaml  validate
echo $'\n\e[1;33m'---------------$'\e[0m'
echo $'\e[1;33m'NCN Spire Postgres Pods Have a Leader$'\e[0m'
echo "Test Name: goss-k8s-postgres-leader"
echo "Description: Validate that spire postgres pods have a leader."
goss -g  /opt/cray/tests/install/ncn/tests/goss-k8s-postgres-leader.yaml  validate

echo $'\n\e[1;33m'-------------------$'\e[0m'
echo $'\e[1;33m'Spire Health Checks Completed$'\e[0m\n'

exit
