#!/usr/bin/env bash
#
# MIT License
#
# (C) Copyright 2021-2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

# Many functions and variables used in this script are defined/set/exported
# in the run-ncn-tests.sh library

echo $'\e[1;33m'NCN Preflight Checks$'\e[0m'
echo $'\e[1;33m'--------------------$'\e[0m'
echo

# The run-ncn-tests.sh library is located in the same directory as the
# current script. Using dirname like this could produce a relative path,
# but that's fine, since we just want to source thie library script.
# Note that this method is not infallible -- in particular, some symbolic
# links can mess it up. But that won't be the case if this was installed
# with the csm-testing RPM.
source "$(dirname -- "$0")/run-ncn-tests.sh"

if ! is_pit_node ; then
    err_exit "These tests can only be run from the LiveCD."
fi

# Find the NCN node names and query the server endpoint
# The get_ncns function is defined in run-ncn-tests.sh
nodes=$(get_ncns --exclude-pit) || exit 1

# The get_ncns function should always give NCNs if its return code was 0, but better safe than sorry
[[ -n ${nodes} ]] || err_exit "No NCNs found"

test_urls=$(goss_endpoint_urls ncn-preflight-tests ${nodes}) || exit 1

print_goss_json_results ${test_urls}
rc=$?

# This script does not exit with non-0 return code just for test failures
[[ $rc -le 1 ]] && exit 0
exit 1
