#!/usr/bin/env bash
#
# MIT License
#
# (C) Copyright 2021-2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

# GOSS_BASE isn't set by default on the NCNs, just on LiveCD
[[ -z ${GOSS_BASE} ]] && export GOSS_BASE="/opt/cray/tests/install/ncn"

export GOSS_LOG_BASE_DIR=/opt/cray/tests/install/logs

source "${GOSS_BASE}/automated/run-ncn-tests.sh"

echo $'\e[1;33m'NCN Run-Time Checks$'\e[0m'
echo $'\e[1;33m'-------------------$'\e[0m'

# Find the NCN node names and query the server endpoint
# The get_ncns function is defined in run-ncn-tests.sh
nodes=$(get_ncns --storage) || exit 1

# The get_ncns function should always give NCNs if its return code was 0, but better safe than sorry
[[ -n ${nodes} ]] || err_exit "No storage NCNs found"

# Query the server endpoint
for node in ${nodes} ; do
	run_ncn_tests "${node}" "9001" "ncn-healthcheck-storage"
	if ! is_pit_node ; then
		run_ncn_tests "${node}" "9006" "ncn-afterpitreboot-healthcheck-storage"
	fi
done

exit
