#!/usr/bin/env bash
#
# (C) Copyright 2021 Hewlett Packard Enterprise Development LP.
# Author: Forrest Jadick
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

function run_preflight_tests {
  node=$1
  port=$2
  echo Running tests against node $'\e[1;33m'$node$'\e[0m'
  url=http://$node:$port/ncn-preflight-tests
  echo Server URL: $url
  results=`curl -s {$url}`
  if [[ $? == 0 ]]; then
    echo
    echo "TEST OUTPUT:"
    echo $results | jq
  else
    echo $'\e[1;31m'ERROR: Server endpoint could not be reached$'\e[0m'
  fi
}

echo $'\e[1;33m'NCN Preflight Automated Tests$'\e[0m'
echo $'\e[1;33m'-----------------------------$'\e[0m'
echo
# find the ncn node names and query the server endpoint
grep NMN /etc/dnsmasq.d/statics.conf | grep -v ncn-m001 | awk -F"," '{print $5}' | \
  while read node ; do run_preflight_tests "$node" "8995" echo ; done

exit