#!/usr/bin/env bash
#
# MIT License
#
# (C) Copyright 2021-2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

# Many functions and variables used in this script are defined/set/exported
# in the run-ncn-tests.sh library

# The run-ncn-tests.sh library is located in the same directory as the
# current script. Using dirname like this could produce a relative path,
# but that's fine, since we just want to source this library script.
# Note that this method is not infallible -- in particular, some symbolic
# links can mess it up. But that won't be the case if this was installed
# with the csm-testing RPM.
source "$(dirname -- "$0")/run-ncn-tests.sh"

# These tests should not be run from the PIT node.
if is_pit_node ; then
    err_exit "These tests cannot be run from the LiveCD."
fi

tmpvars=$(create_goss_variable_file) || exit 1

echo $'\e[1;33m'NCN Postgres Tests$'\e[0m'
echo $'\e[1;33m'---------------$'\e[0m'

postgresClusters="$(kubectl get postgresql -A | awk '/postgres/ || NR==1' | \
                    grep -v NAME | awk '{print $1","$2}')"
for postgresCluster in ${postgresClusters}; do
  # $tmpvars is set by the create_tmpvars_file function earlier
  #shellcheck disable=SC2154
  CLUSTER_NAME=$(echo ${postgresCluster} | awk -F, '{print $2;}') \
  CLUSTER_NS=$(echo ${postgresCluster} | awk -F, '{print $1;}') \
  goss -g \
    "${GOSS_BASE}/suites/ncn-postgres-tests.yaml" \
    --vars "${tmpvars}" \
    validate
done

exit
