#!/usr/bin/env bash
#
# MIT License
#
# (C) Copyright 2021-2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# Validates that all nodes have joined the Kubernetes cluster.

nodes=$(grep -ohE 'ncn-[m,w,s]([0-9]{3})' /etc/dnsmasq.d/statics.conf  | awk '!a[$0]++' | grep -v ncn-m001)
fail=0

for node in $nodes; do
  test=$(kubectl get nodes | grep $node)
  if [[ $? != 0 ]]; then
    echo ERROR! Node not in cluster: $node
    fail=1
  fi
done

if [[ $fail -eq 1 ]]; then
  echo
  echo Kubernetes cluster node check failed!
  exit 1
else
  echo
  echo Kubernetes cluster node check passed!
  exit 0
fi