#!/usr/bin/env bash

# (C) Copyright 2022 Hewlett Packard Enterprise Development LP.
#
# MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

set -e

# wipe ceph storage
if [[ ! -f /var/lib/ceph/*-* ]]; then
  exit 0
fi
FSID=$(basename $(ls -d /var/lib/ceph/*-*))
cephadm rm-cluster --fsid $FSID --force
vgremove -f --select 'vg_name=~ceph*'
umount /etc/ceph /var/lib/containers /var/lib/ceph
vgremove -f metalvg0
sgdisk --zap-all /dev/sd*
wipefs -fa /dev/sd*

# wipe k8s storage
if [[ ! -f /dev/sd* ]]; then
  exit 0
fi
sgdis --zap-all /dev/sd*
wipefs -fa /dev/sd*

exit