name: backport

on:
  issue_comment:
    types:
      - created

jobs:
  backport:
    runs-on: self-hosted
    if: github.event.issue.pull_request
    steps:
      - run: |
          echo "Modified action!"
          echo "Runs on: ${RUNNER_NAME}"
      - uses: Cray-HPE/backport-command-action@main
